-- =====================================================================
-- MEDALLION ARCHITECTURE  |  LAYER 3 of 3  |  GOLD
-- =====================================================================
-- Purpose : Business-ready star schema for reporting and Power BI.
-- Source  : e_commerce.silver.*
-- Target  : e_commerce.gold.*
-- Rule    : Gold = RESHAPE + a few NEW COLUMNS.
--           This is the ONLY layer where new columns are created.
--
-- Star schema built here
--   3 dimensions : dim_date, dim_customer, dim_product
--   3 facts      : fact_sales, fact_reviews, fact_events
--   1 summary    : agg_sales_summary
--
-- The 5 new columns added in this layer
--   1. dim_customer.signup_year   - year taken from signup_date
--   2. dim_product.price_band     - Low / Medium / High based on price
--   3. fact_sales.is_completed    - Y/N flag for completed orders
--   4. fact_reviews.sentiment     - Positive / Neutral / Negative from rating
--   5. fact_events.is_purchase    - Y/N flag for purchase events
--   (dim_date is a brand new table, built from a date range)
--
-- Note on surrogate keys
--   customer_key, product_key and date_key are simple numbers that
--   replace the text IDs. They are generated in the notebook using
--   row_number(), so you can see exactly where each value comes from.
-- =====================================================================

-- Run this only if you want a clean restart:
-- DROP SCHEMA IF EXISTS e_commerce.gold CASCADE;

CREATE SCHEMA IF NOT EXISTS e_commerce.gold
  COMMENT 'Gold layer - star schema for reporting';

USE CATALOG e_commerce;
USE SCHEMA gold;


-- =====================================================================
-- DIMENSION TABLES
-- =====================================================================

-- ---------------------------------------------------------------------
-- Dimension 1 : dim_date
-- A brand new table. Not present in bronze or silver.
-- One row per calendar day, built from a date range.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS e_commerce.gold.dim_date (
  date_key     INT     NOT NULL COMMENT 'Date as a number, example 20250714',
  full_date    DATE             COMMENT 'The actual date',
  year         INT              COMMENT 'NEW - year, example 2025',
  month        INT              COMMENT 'NEW - month number 1 to 12',
  month_name   STRING           COMMENT 'NEW - month name, example January',
  quarter      INT              COMMENT 'NEW - quarter 1 to 4',
  day_name     STRING           COMMENT 'NEW - day name, example Monday',
  is_weekend   STRING           COMMENT 'NEW - Y if Saturday or Sunday, else N',

  CONSTRAINT pk_dim_date PRIMARY KEY (date_key)
)
USING DELTA
COMMENT 'Gold - date dimension, one row per day';


-- ---------------------------------------------------------------------
-- Dimension 2 : dim_customer
-- Source: silver.users
-- NEW COLUMNS: customer_key, signup_year
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS e_commerce.gold.dim_customer (
  customer_key  BIGINT NOT NULL COMMENT 'NEW - surrogate key, generated by row_number()',
  user_id       STRING          COMMENT 'Original user ID from silver',
  name          STRING          COMMENT 'Customer name',
  email         STRING          COMMENT 'Email address',
  gender        STRING          COMMENT 'Gender',
  city          STRING          COMMENT 'City',
  signup_date   DATE            COMMENT 'Registration date',
  signup_year   INT             COMMENT 'NEW - year part of signup_date',

  CONSTRAINT pk_dim_customer PRIMARY KEY (customer_key)
)
USING DELTA
COMMENT 'Gold - customer dimension';


-- ---------------------------------------------------------------------
-- Dimension 3 : dim_product
-- Source: silver.products
-- NEW COLUMNS: product_key, price_band
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS e_commerce.gold.dim_product (
  product_key   BIGINT NOT NULL COMMENT 'NEW - surrogate key, generated by row_number()',
  product_id    STRING          COMMENT 'Original product ID from silver',
  product_name  STRING          COMMENT 'Product name',
  category      STRING          COMMENT 'Product category',
  brand         STRING          COMMENT 'Brand name',
  price         DECIMAL(10,2)   COMMENT 'Product price',
  rating        DECIMAL(3,2)    COMMENT 'Product rating',
  price_band    STRING          COMMENT 'NEW - Low if price<100, Medium if <500, else High',

  CONSTRAINT pk_dim_product PRIMARY KEY (product_key)
)
USING DELTA
COMMENT 'Gold - product dimension';


-- =====================================================================
-- FACT TABLES
-- =====================================================================

-- ---------------------------------------------------------------------
-- Fact 1 : fact_sales
-- Source: silver.order_items joined to silver.orders
-- NEW COLUMNS: customer_key, product_key, date_key, is_completed
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS e_commerce.gold.fact_sales (
  order_item_id  STRING         COMMENT 'Order item ID from silver',
  order_id       STRING         COMMENT 'Order ID from silver',
  customer_key   BIGINT         COMMENT 'NEW - links to dim_customer',
  product_key    BIGINT         COMMENT 'NEW - links to dim_product',
  date_key       INT            COMMENT 'NEW - links to dim_date',
  quantity       INT            COMMENT 'Units purchased',
  item_price     DECIMAL(10,2)  COMMENT 'Price per unit',
  item_total     DECIMAL(12,2)  COMMENT 'Line total value',
  order_status   STRING         COMMENT 'Order status from silver.orders',
  is_completed   STRING         COMMENT 'NEW - Y if order_status is completed, else N',

  CONSTRAINT fk_sales_customer FOREIGN KEY (customer_key) REFERENCES e_commerce.gold.dim_customer (customer_key),
  CONSTRAINT fk_sales_product  FOREIGN KEY (product_key)  REFERENCES e_commerce.gold.dim_product (product_key),
  CONSTRAINT fk_sales_date     FOREIGN KEY (date_key)     REFERENCES e_commerce.gold.dim_date (date_key)
)
USING DELTA
COMMENT 'Gold - sales fact, one row per order line';


-- ---------------------------------------------------------------------
-- Fact 2 : fact_reviews
-- Source: silver.reviews
-- NEW COLUMNS: customer_key, product_key, date_key, sentiment
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS e_commerce.gold.fact_reviews (
  review_id     STRING  COMMENT 'Review ID from silver',
  order_id      STRING  COMMENT 'Related order',
  customer_key  BIGINT  COMMENT 'NEW - links to dim_customer',
  product_key   BIGINT  COMMENT 'NEW - links to dim_product',
  date_key      INT     COMMENT 'NEW - links to dim_date',
  rating        INT     COMMENT 'Star rating 1 to 5',
  review_text   STRING  COMMENT 'Review comment',
  sentiment     STRING  COMMENT 'NEW - Negative if rating<=2, Neutral if 3, else Positive',

  CONSTRAINT fk_reviews_customer FOREIGN KEY (customer_key) REFERENCES e_commerce.gold.dim_customer (customer_key),
  CONSTRAINT fk_reviews_product  FOREIGN KEY (product_key)  REFERENCES e_commerce.gold.dim_product (product_key),
  CONSTRAINT fk_reviews_date     FOREIGN KEY (date_key)     REFERENCES e_commerce.gold.dim_date (date_key)
)
USING DELTA
COMMENT 'Gold - reviews fact, one row per review';


-- ---------------------------------------------------------------------
-- Fact 3 : fact_events
-- Source: silver.events
-- NEW COLUMNS: customer_key, product_key, date_key, is_purchase
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS e_commerce.gold.fact_events (
  event_id         STRING     COMMENT 'Event ID from silver',
  customer_key     BIGINT     COMMENT 'NEW - links to dim_customer',
  product_key      BIGINT     COMMENT 'NEW - links to dim_product',
  date_key         INT        COMMENT 'NEW - links to dim_date',
  event_type       STRING     COMMENT 'view, cart, wishlist or purchase',
  event_timestamp  TIMESTAMP  COMMENT 'Event date and time',
  is_purchase      STRING     COMMENT 'NEW - Y if event_type is purchase, else N',

  CONSTRAINT fk_events_customer FOREIGN KEY (customer_key) REFERENCES e_commerce.gold.dim_customer (customer_key),
  CONSTRAINT fk_events_product  FOREIGN KEY (product_key)  REFERENCES e_commerce.gold.dim_product (product_key),
  CONSTRAINT fk_events_date     FOREIGN KEY (date_key)     REFERENCES e_commerce.gold.dim_date (date_key)
)
USING DELTA
COMMENT 'Gold - events fact, one row per event';


-- =====================================================================
-- SUMMARY TABLE
-- =====================================================================

-- ---------------------------------------------------------------------
-- agg_sales_summary
-- Source: gold.fact_sales joined to gold.dim_product
-- A small pre-calculated table so reports do not scan the full fact.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS e_commerce.gold.agg_sales_summary (
  date_key        INT            COMMENT 'Links to dim_date',
  category        STRING         COMMENT 'Product category',
  total_orders    BIGINT         COMMENT 'NEW - count of distinct orders',
  total_quantity  BIGINT         COMMENT 'NEW - sum of quantity',
  total_revenue   DECIMAL(14,2)  COMMENT 'NEW - sum of item_total for completed orders'
)
USING DELTA
COMMENT 'Gold - daily sales summary by category';


-- ---------------------------------------------------------------------
-- Check the tables were created
-- ---------------------------------------------------------------------
SHOW TABLES IN e_commerce.gold;
